# Generated by Django 4.1.5 on 2023-02-21 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studmanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addcourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('fees', models.CharField(max_length=20000000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(max_length=100000000)),
            ],
        ),
    ]
