# Generated by Django 4.1.5 on 2023-02-22 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studmanagement', '0002_addcourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addstudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=100)),
                ('semail', models.EmailField(max_length=254)),
                ('smobile', models.CharField(max_length=100)),
                ('saddress', models.CharField(max_length=100)),
                ('scollege', models.CharField(max_length=100)),
                ('sdegree', models.CharField(max_length=100)),
                ('total_amount', models.IntegerField()),
                ('paid_amount', models.IntegerField()),
                ('due_amount', models.IntegerField()),
                ('scourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studmanagement.addcourse')),
            ],
        ),
    ]
