# Generated by Django 4.1.5 on 2023-02-24 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studmanagement', '0003_addstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addteachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=50)),
                ('employee_id', models.IntegerField()),
                ('joining_date', models.DateField()),
                ('experiance', models.CharField(max_length=50)),
                ('temail', models.EmailField(max_length=254)),
                ('tcontact', models.IntegerField()),
                ('tpassword', models.CharField(max_length=50)),
                ('tgender', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=50)),
                ('tupload_image', models.ImageField(upload_to='teacher/')),
                ('is_active', models.BooleanField(default=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('tcourses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studmanagement.addcourse')),
            ],
        ),
    ]
