# Generated by Django 4.1.5 on 2023-02-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studmanagement', '0004_addteachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addteachers',
            name='tcontact',
            field=models.IntegerField(max_length=20),
        ),
    ]
