from django.urls import path,re_path
from . import views
urlpatterns = [
    path('', views.index),
    path('sign_in/', views.sign_in),
    path('courses/', views.courses),
    path('addcourse/', views.addcourse),
    path('updateform/<int:uid>/', views.updatepage),
    path('updatecourse/', views.course_update),
    # path('delete/<int:uid>/',views.delete),
    re_path(r'^delete/(?P<pk>[0-9]+)/$',views.delete,name="delete"),
    # path('updatecourse/<int:uid>/',views.courseupdate),
    # path('updatecoursedata/',views.course_update),
    path('dashboard/', views.dashboard),
    path('employees/', views.employees),
    path('notifications/', views.notifications),
    path('pg_dashboard/', views.pg_dashboard),
    path('profile/', views.profile),
    path('sign-up/', views.sign_up),
    path('signup_data/', views.signup_updata),
    path('tables/', views.tables),
    path('tenants/', views.tenants),
    path('viewstudents/', views.viewstudents),
    # path('updateform2/',views.updateform2),
    path('addstudent/',views.addstudent),
]
